package com.splitsync.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    UNAUTHORIZED,
    INVALID_CREDENTIALS,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    EMAIL_ALREADY_REGISTERED,
    OUTSTANDING_BALANCE,
    INVITATION_NOT_PENDING,
    SETTLEMENT_NOT_PAYABLE,
    UNSUPPORTED_CURRENCY,
    FX_UNAVAILABLE,
    IDEMPOTENCY_KEY_REUSED,
    REQUEST_IN_PROGRESS,
    RATE_LIMITED,
    USERNAME_TAKEN,
    INVALID_TOKEN,
    EMAIL_ALREADY_VERIFIED,
    RECEIPT_UNREADABLE,
    RECEIPT_SCAN_UNAVAILABLE,
    INTERNAL_ERROR
}
